[package]
name = "lindenmayer-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lindenmayer-renderer = { path = "../lindenmayer-renderer" }
csscolorparser = "0.6.2"